# Generated by Django 3.2.6 on 2022-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledetails',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='mname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
