# Generated by Django 3.2.6 on 2022-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220619_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='elem_grade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='profe_grade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='secd_grade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='univ_grade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
